version: '3.3'

services:
  py:
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 webserver.py -v"]
    ports:
      - 5678:5678
    environment:
      FLASK_ENV: development
