version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #MYSQL_ALLOW_EMPTY_PASSWORD: 'Yes'
      #MYSQL_RANDOM_ROOT_PASSWORD: 'Yes'
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf

  py:
    image: flask_app
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 5000:5000
    #restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #FLASK_APP: webserver
    working_dir: /usr/src/app
    command: ["sh", "-c", "python webserver.py"]
    volumes:
      - ./app/:/usr/src/app

volumes:
  db_data: {}
